# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marat/proga/TheLimitOfDreams

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marat/proga/TheLimitOfDreams

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marat/proga/TheLimitOfDreams/CMakeFiles /Users/marat/proga/TheLimitOfDreams//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marat/proga/TheLimitOfDreams/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TheLimitOfDreams

# Build rule for target.
TheLimitOfDreams: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TheLimitOfDreams
.PHONY : TheLimitOfDreams

# fast build rule for target.
TheLimitOfDreams/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/build
.PHONY : TheLimitOfDreams/fast

Source/Game.Console.o: Source/Game.Console.cpp.o
.PHONY : Source/Game.Console.o

# target to build an object file
Source/Game.Console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Console.cpp.o
.PHONY : Source/Game.Console.cpp.o

Source/Game.Console.i: Source/Game.Console.cpp.i
.PHONY : Source/Game.Console.i

# target to preprocess a source file
Source/Game.Console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Console.cpp.i
.PHONY : Source/Game.Console.cpp.i

Source/Game.Console.s: Source/Game.Console.cpp.s
.PHONY : Source/Game.Console.s

# target to generate assembly for a file
Source/Game.Console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Console.cpp.s
.PHONY : Source/Game.Console.cpp.s

Source/Game.Terrain.o: Source/Game.Terrain.cpp.o
.PHONY : Source/Game.Terrain.o

# target to build an object file
Source/Game.Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Terrain.cpp.o
.PHONY : Source/Game.Terrain.cpp.o

Source/Game.Terrain.i: Source/Game.Terrain.cpp.i
.PHONY : Source/Game.Terrain.i

# target to preprocess a source file
Source/Game.Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Terrain.cpp.i
.PHONY : Source/Game.Terrain.cpp.i

Source/Game.Terrain.s: Source/Game.Terrain.cpp.s
.PHONY : Source/Game.Terrain.s

# target to generate assembly for a file
Source/Game.Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.Terrain.cpp.s
.PHONY : Source/Game.Terrain.cpp.s

Source/Game.o: Source/Game.cpp.o
.PHONY : Source/Game.o

# target to build an object file
Source/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.cpp.o
.PHONY : Source/Game.cpp.o

Source/Game.i: Source/Game.cpp.i
.PHONY : Source/Game.i

# target to preprocess a source file
Source/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.cpp.i
.PHONY : Source/Game.cpp.i

Source/Game.s: Source/Game.cpp.s
.PHONY : Source/Game.s

# target to generate assembly for a file
Source/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/Game.cpp.s
.PHONY : Source/Game.cpp.s

Source/PauseMenu.o: Source/PauseMenu.cpp.o
.PHONY : Source/PauseMenu.o

# target to build an object file
Source/PauseMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/PauseMenu.cpp.o
.PHONY : Source/PauseMenu.cpp.o

Source/PauseMenu.i: Source/PauseMenu.cpp.i
.PHONY : Source/PauseMenu.i

# target to preprocess a source file
Source/PauseMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/PauseMenu.cpp.i
.PHONY : Source/PauseMenu.cpp.i

Source/PauseMenu.s: Source/PauseMenu.cpp.s
.PHONY : Source/PauseMenu.s

# target to generate assembly for a file
Source/PauseMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/PauseMenu.cpp.s
.PHONY : Source/PauseMenu.cpp.s

Source/main.o: Source/main.cpp.o
.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i
.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s
.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TheLimitOfDreams.dir/build.make CMakeFiles/TheLimitOfDreams.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TheLimitOfDreams"
	@echo "... Source/Game.Console.o"
	@echo "... Source/Game.Console.i"
	@echo "... Source/Game.Console.s"
	@echo "... Source/Game.Terrain.o"
	@echo "... Source/Game.Terrain.i"
	@echo "... Source/Game.Terrain.s"
	@echo "... Source/Game.o"
	@echo "... Source/Game.i"
	@echo "... Source/Game.s"
	@echo "... Source/PauseMenu.o"
	@echo "... Source/PauseMenu.i"
	@echo "... Source/PauseMenu.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

