include_guard()

set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/project.json)

if(CMAKE_MODULE_PATH)
    foreach(module_path ${CMAKE_MODULE_PATH})
        cmake_path(SET module_engine_version_cmake_path "${module_path}/o3deConfigVersion.cmake")
        if(EXISTS "${module_engine_version_cmake_path}")
            include("${module_engine_version_cmake_path}")
            if(PACKAGE_VERSION_COMPATIBLE)
                message(STATUS "Selecting engine from CMAKE_MODULE_PATH '${module_path}'")
                return()
            endif()
        endif()
    endforeach()
endif()

cmake_path(SET O3DE_USER_PROJECT_JSON_PATH ${CMAKE_CURRENT_SOURCE_DIR}/user/project.json)
if(EXISTS "${O3DE_USER_PROJECT_JSON_PATH}")
    file(READ "${O3DE_USER_PROJECT_JSON_PATH}" user_project_json)
    if(user_project_json)
        string(JSON user_project_engine_path ERROR_VARIABLE json_error GET ${user_project_json} engine_path)
        if(user_project_engine_path AND NOT json_error)
            cmake_path(SET user_engine_version_cmake_path "${user_project_engine_path}/cmake/o3deConfigVersion.cmake")
            if(EXISTS "${user_engine_version_cmake_path}")
                include("${user_engine_version_cmake_path}")
                if(PACKAGE_VERSION_COMPATIBLE)
                    message(STATUS "Selecting engine '${user_project_engine_path}' from user/project.json")
                    list(APPEND CMAKE_MODULE_PATH "${user_project_engine_path}/cmake")
                    return()
                endif()
            endif()
        endif()
    endif()
endif()

if(DEFINED ENV{USERPROFILE} AND EXISTS $ENV{USERPROFILE})
    set(manifest_path $ENV{USERPROFILE}/.o3de/o3de_manifest.json)
else()
    set(manifest_path $ENV{HOME}/.o3de/o3de_manifest.json)
endif()

if(EXISTS ${manifest_path})
    file(READ ${manifest_path} manifest_json)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${manifest_path})

    string(JSON engines_count ERROR_VARIABLE json_error LENGTH ${manifest_json} engines)
    if(NOT json_error)
        math(EXPR engines_count "${engines_count}-1")
        foreach(array_index RANGE ${engines_count})
            string(JSON manifest_engine_path ERROR_VARIABLE json_error GET ${manifest_json} engines "${array_index}")
            if(NOT json_error)
                list(APPEND O3DE_ENGINE_PATHS ${manifest_engine_path})
            endif()
        endforeach()
    endif()
endif()

set(O3DE_MOST_COMPATIBLE_ENGINE_PATH "")
set(O3DE_MOST_COMPATIBLE_ENGINE_VERSION "")
foreach(manifest_engine_path IN LISTS O3DE_ENGINE_PATHS)
    cmake_path(SET version_cmake_path "${manifest_engine_path}/cmake/o3deConfigVersion.cmake")
    if(NOT EXISTS "${version_cmake_path}")
        continue()
    endif()

    unset(PACKAGE_VERSION)
    unset(PACKAGE_VERSION_COMPATIBLE)
    include("${version_cmake_path}")

    if(PACKAGE_VERSION_COMPATIBLE)
        if(NOT O3DE_MOST_COMPATIBLE_ENGINE_PATH)
            set(O3DE_MOST_COMPATIBLE_ENGINE_PATH "${manifest_engine_path}")
            set(O3DE_MOST_COMPATIBLE_ENGINE_VERSION ${PACKAGE_VERSION})
        elseif(${PACKAGE_VERSION} VERSION_GREATER ${O3DE_MOST_COMPATIBLE_ENGINE_VERSION})
            set(O3DE_MOST_COMPATIBLE_ENGINE_PATH "${manifest_engine_path}")
            set(O3DE_MOST_COMPATIBLE_ENGINE_VERSION ${PACKAGE_VERSION})
        endif()
    endif()
endforeach()

if(O3DE_MOST_COMPATIBLE_ENGINE_PATH)
    set(PACKAGE_VERSION_COMPATIBLE True)
    set(PACKAGE_VERSION O3DE_MOST_COMPATIBLE_ENGINE_VERSION)
    list(APPEND CMAKE_MODULE_PATH "${O3DE_MOST_COMPATIBLE_ENGINE_PATH}/cmake")
    message(STATUS "Selecting engine '${O3DE_MOST_COMPATIBLE_ENGINE_PATH}'")
    return()
endif()

message(FATAL_ERROR "No compatible O3DE engine found. Register O3DE 2510.2 and retry configure.")
